import type { Metadata } from 'next';

import { fontClasses } from '@/configs/fonts';
import { LayoutMain } from '@/layouts/main/MainLayout';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontClasses}>
        <LayoutMain>{children}</LayoutMain>
      </body>
    </html>
  );
}
