import type { Metadata } from 'next';
import { Geist, Geist_Mono, Sarabun } from 'next/font/google';

import { LayoutMain } from '@/layouts/main/MainLayout';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const sarabun = Sarabun({
  variable: '--font-sarabun',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${sarabun.variable}`}>
        <LayoutMain>{children}</LayoutMain>
      </body>
    </html>
  );
}
